services:
  postgres:
    image: postgres:16
    container_name: aviate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "54321"
      POSTGRES_DB: Aviate
    ports:
      - "5435:5432"
    volumes:
      - aviateapi_postgres_data_new:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Aviate.API/Dockerfile
    container_name: aviate_api
    ports:
      - "5004:5004"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Aviate;Username=postgres;Password=54321

  frontend:
    container_name: frontend_aviate
    build:
      context: ./Aviate.Frontend/aviate
      target: prod
    ports:
      - "3004:3004"

volumes:
  aviateapi_postgres_data_new:
