services:
  postgres:
    image: postgres:16
    container_name: aviate_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "54321"
      POSTGRES_DB: Aviate
    ports:
      - "5435:5432"
    volumes:
      - aviateapi_postgres_data_new:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Aviate.API/Dockerfile
    container_name: aviate_api
    ports:
      - "5004:5004"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Aviate;Username=postgres;Password=54321

  frontend:
    container_name: frontend_aviate
    build:
      context: ./Aviate.Frontend/aviate
      target: prod
    ports:
      - "3004:3004"

  minio:
    image: minio/minio
    container_name: aviate_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  aviateapi_postgres_data_new:
  minio_data:
